balena-io/contracts

- contracts/sw.os+arch.sw/fedora+armv7hf/base-dependencies.tpl
- contracts/sw.os+arch.sw/fedora/base-dependencies.tpl
- contracts/sw.os/fedora/contract.json
> fedora: Set Fedora 30 as latest and add Fedora 31

- contracts/hw.device-type/j120-tx2/contract.json
> device: Add support for Auvidea j120 TX2

- contracts/sw.stack/node/contract.json
> node: Add v12.8.1 10.16.3 and v8.16.1

- contracts/hw.device-type/raspberrypi4-64/contract.json
- contracts/sw.os+hw.device-type/alpine+raspberrypi3-64/dependencies.tpl
- contracts/sw.os+hw.device-type/alpine+raspberrypi4-64/dependencies.tpl
- contracts/sw.os+hw.device-type/debian+raspberrypi3-64/dependencies.tpl
- contracts/sw.os+hw.device-type/debian+raspberrypi3-64/distro-config.tpl
- contracts/sw.os+hw.device-type/debian+raspberrypi4-64/dependencies.tpl
- contracts/sw.os+hw.device-type/debian+raspberrypi4-64/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+raspberrypi3-64/dependencies.tpl
- contracts/sw.os+hw.device-type/ubuntu+raspberrypi4-64/dependencies.tpl
- contracts/sw.os+hw.device-type/ubuntu@trusty+raspberrypi3-64/dependencies.tpl
- contracts/sw.os+hw.device-type/ubuntu@trusty+raspberrypi4-64/dependencies.tpl
> device: Add support for raspberrypi4-64

- contracts/sw.stack/node/contract.json
> node: Add support for v12.10.0

- contracts/sw.stack/node/contract.json
> node: Add support for Node v12.11.0

- contracts/sw.stack/golang/contract.json
> go: Add v1.13.1 and v1.12.10

- contracts/sw.os/alpine/contract.json
- contracts/sw.os/debian/contract.json
- contracts/sw.os/fedora/contract.json
- contracts/sw.os/ubuntu/contract.json
Connects to https://github.com/balena-io-library/base-images/pull/598
> test: Update OS version test

- contracts/hw.device-type/surface-go/contract.json
> device: Add support for Surface Go

- contracts/sw.os+arch.sw/balena-xbuild.tpl
- contracts/sw.os/alpine/contract.json
- contracts/sw.os/debian/contract.json
- contracts/sw.os/fedora/contract.json
- contracts/sw.os/ubuntu/contract.json
- contracts/sw.stack/golang/contract.json
- contracts/sw.stack/node/contract.json
This PR has the following changes:
- node: Add v13.1.0
- golang: Add v1.12.13 and v1.13.4
> Few base image updates

- contracts/hw.device-type/coral-dev/contract.json
Add support for new device type - coral-dev
> device: Add Google Coral Dev Board

- contracts/sw.stack/dotnet/contract.json
> dotnet: Add v3.1.0 v2.2.8 and v2.1.14

- contracts/sw.stack/node/contract.json
> Add node v13.11.0 and update yarn to v1.22.4

- contracts/hw.device-type/skx2/contract.json
> device: Add support for SKX2

- contracts/sw.stack/node/contract.json
> Add node v13.12.0

- contracts/sw.os+arch.sw/ubuntu@focal/base-dependencies.tpl
- contracts/sw.os/ubuntu/contract.json
This release is only for armv7hf, aarch64 and amd64
> Add support for ubuntu focal (20.04)

- contracts/sw.stack/node/contract.json
> Add node v12.16.2 and v10.20.0

- contracts/hw.device-type/genericx86-64-ext/contract.json
> device: Add support for Generic x86_64

- contracts/hw.device-type/imx8mm-var-dart-plt/contract.json
> device: Add support for Variscite DART MX8M Mini PLT

- contracts/sw.blob/qemu/contract.json
> Update QEMU to v4.0.0+balena2

- contracts/sw.stack/node/contract.json
> Add node v12.16.3

- contracts/sw.stack/node/contract.json
- contracts/sw.stack/python/contract.json
- Add node v14.2.0
- Add Python v3.8.3
> Few base images updates

- contracts/hw.device-type/aio-3288c/contract.json
- contracts/hw.device-type/firefly-rk3288/contract.json
- contracts/hw.device-type/photon-nano/contract.json
These come from:
- https://github.com/balena-os/balena-rockchip-rk3288/
- https://github.com/balena-os/balena-jetson/blob/master/photon-nano.coffee
> Add recent community contributed devices

- contracts/hw.device-type/imx8mm-var-dart-nrt/contract.json
> device: Add support for Variscite DART MX8M Mini NRT

- contracts/hw.device-type/jetson-nano-emmc/contract.json
- contracts/hw.device-type/jetson-nano/contract.json
- contracts/hw.device-type/jetson-xavier-nx-devkit-emmc/contract.json
- contracts/hw.device-type/photon-xavier-nx/contract.json
> Add new boards

- contracts/sw.stack/python/contract.json
> Add Python v3.8.5

- contracts/hw.device-type/edge/contract.json
- contracts/hw.device-type/generic/contract.json
> Add a couple of discontinued device types for completeness

- contracts/hw.device-type/am571x-evm/contract.json
- contracts/hw.device-type/apalis-imx6q/contract.json
- contracts/hw.device-type/artik5/contract.json
- contracts/hw.device-type/beaglebone-green-wifi/contract.json
- contracts/hw.device-type/cl-som-imx8/contract.json
- contracts/hw.device-type/colibri-imx6dl/contract.json
- contracts/hw.device-type/coral-dev/contract.json
- contracts/hw.device-type/cybertan-ze250/contract.json
- contracts/hw.device-type/imx6ul-var-dart/contract.json
- contracts/hw.device-type/odroid-c1/contract.json
- contracts/hw.device-type/odroid-xu4/contract.json
- contracts/hw.device-type/qemux86-64/contract.json
- contracts/hw.device-type/qemux86/contract.json
- contracts/hw.device-type/raspberry-pi/contract.json
- contracts/hw.device-type/raspberrypi3-64/contract.json
- contracts/hw.device-type/surface-pro-6/contract.json
- contracts/hw.device-type/via-vab820-quad/contract.json
- contracts/hw.device-type/zynq-xz702/contract.json
> Update device type names to match the existing ones in balena API

- contracts/hw.device-type/revpi-connect/contract.json
> revpi-connect: Add Revolution Pi Connect device type

- contracts/sw.stack/node/contract.json
- contracts/sw.stack/python/contract.json
- Add node v14.13.1 and v12.19.0.
- Add Python v3.9.0 v3.8.6 v3.7.9 v3.6.12 and v3.5.10.
> Base images updates

- contracts/hw.device-type/nitrogen8mm-dwe/contract.json
> Update nitrogen8mm-dwe name to HUB3

- contracts/sw.stack/node/contract.json
> Add node v15.1.0

- contracts/sw.stack/node/contract.json
> Add node v15.2.1 v14.15.1 and v12.19.1

- contracts/hw.device-type/beaglebone-black/contract.json
- contracts/hw.device-type/beaglebone-green-wifi/contract.json
- contracts/hw.device-type/beaglebone-green/contract.json
- contracts/hw.device-type/beaglebone-pocket/contract.json
> Fix mistaken logo path names

- contracts/hw.device-type/beaglebone-green-gateway/contract.json
> Fix logo path for beaglebone green gateway

- contracts/sw.os+hw.device-type/alpine+raspberrypi400-64/dependencies.tpl
- contracts/sw.os+hw.device-type/debian+jetson-xavier-nx-devkit/distro-config.tpl
- contracts/sw.os+hw.device-type/debian+raspberrypi400-64/dependencies.tpl
- contracts/sw.os+hw.device-type/debian+raspberrypi400-64/distro-config.tpl
- contracts/sw.os+hw.device-type/debian@buster+raspberrypi3-64/dependencies.tpl
- contracts/sw.os+hw.device-type/debian@buster+raspberrypi4-64/dependencies.tpl
- contracts/sw.os+hw.device-type/debian@buster+raspberrypi400-64/dependencies.tpl
- contracts/sw.os+hw.device-type/ubuntu+jetson-xavier-nx-devkit/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+raspberrypi400-64/dependencies.tpl
- contracts/sw.os+hw.device-type/ubuntu@trusty+raspberrypi400-64/dependencies.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@5.0-aspnet+debian/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@5.0-aspnet+debian/run.tpl
- contracts/sw.stack/dotnet/contract.json
- contracts/sw.stack/node/contract.json
```
- Add node v10.23.1 v12.20.1 v14.15.4 v15.5.1
- Add partials for dotnet 5.0-aspnet
- Add partials for rapsberrypi400-64
- Add partials for jetson-xavier-nx-devkit 
```
> Various base images updates

- contracts/sw.blob/qemu/contract.json
> Update QEMU to v5.2.0+balena1

- contracts/hw.device-family/tinkerboard/contract.json
- contracts/hw.device-manufacturer/asus/contract.json
- contracts/hw.device-type/asus-tinker-board-s/contract.json
- contracts/hw.device-type/asus-tinker-board/contract.json
> Add sample device family and device manufacturers

- contracts/hw.device-type/nebra-hnt/contract.json
> nebra-hnt: Make device private

- contracts/hw.device-family/upboard/contract.json
- contracts/hw.device-manufacturer/aaeon/contract.json
- contracts/hw.device-type/up-board/contract.json
- contracts/hw.device-type/up-core-plus/contract.json
- contracts/hw.device-type/up-core/contract.json
- contracts/hw.device-type/up-squared/contract.json
> Add UP board family and manufacturer info

- contracts/sw.stack/node/contract.json
Drop node v10.x since it is EOL
> Add node v16.4.1 v14.17.2 and v12.22.2

- contracts/sw.stack/golang/contract.json
> Update test script for Golang base images

- contracts/sw.stack/node/contract.json
> Add node v14.18.0

- contracts/sw.stack/python/contract.json
> Add Python v3.10.0

- contracts/sw.stack/node/contract.json
> Add node v16.11.1 v14.18.1 and v12.22.7

- contracts/sw.stack/dotnet/contract.json
> Fix wrong version number in dotnet contract

- .versionbot/CHANGELOG.yml
Signed-off-by: Kyle Harding <kyle@balena.io>
Create CHANGELOG.yml with generate-changelog.sh script
How I generated this file:
```
wget https://raw.githubusercontent.com/product-os/versionist/master/scripts/generate-changelog.sh
chmod +x generate-changelog.sh
wget https://github.com/mikefarah/yq/releases/download/3.0.1/yq_linux_amd64 -O yq
chmod +x yq
PATH="${PWD}:$PATH" GH_TOKEN=REDACTED ./generate-changelog.sh .
```
> Enable nested changelogs

- contracts/sw.stack+sw.os+hw.device-type/openjdk@17-jdk+debian/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/openjdk@17-jdk+debian/run.tpl
> Add partials for OpenJDK 17 images

- contracts/hw.device-type/aio-3288c/contract.json
- contracts/hw.device-type/am571x-evm/contract.json
- contracts/hw.device-type/asus-tinker-board-s/contract.json
- contracts/hw.device-type/asus-tinker-board/contract.json
- contracts/hw.device-type/bananapi-m1-plus/contract.json
- contracts/hw.device-type/firefly-rk3288/contract.json
- contracts/hw.device-type/imx6ul-var-dart/contract.json
- contracts/hw.device-type/imx7-var-som/contract.json
- contracts/hw.device-type/isg-503/contract.json
- contracts/hw.device-type/kitra710/contract.json
- contracts/hw.device-type/nanopi-neo-air/contract.json
- contracts/hw.device-type/odroid-c1/contract.json
- contracts/hw.device-type/odroid-xu4/contract.json
- contracts/hw.device-type/parallella/contract.json
- contracts/hw.device-type/rockpi-4b-rk3399/contract.json
- contracts/hw.device-type/up-board/contract.json
- contracts/hw.device-type/zynq-xz702/contract.json
Signed-off-by: Micah Halter <micah@balena.io>
> Fixed incorrect led status

- contracts/hw.device-type/odyssey-x86/contract.json
Signed-off-by: Lakshantha Dissanayake <lakshanthad@seeed.cc>
> contract.json: Change pretty device type name

- contracts/sw.stack/node/contract.json
> Add node v17.5.0 and v16.14.0

- contracts/hw.device-type/rockpro64/contract.json
> hw.device-type: Fix rockpro64 logo path

- contracts/sw.stack+sw.os+hw.device-type/python+alpine/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/python+alpine/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/python+debian/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/python+debian/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/python+ubuntu/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/python+ubuntu/run.tpl
- contracts/sw.stack/python/contract.json
> Install pip and setuptools using get-pip.py

- contracts/hw.device-type/topic-tdpzu9/contract.json
- contracts/hw.device-type/topic-tdpzu9/tdpzu9.svg
Signed-off-by: Francois Loubser <francois.loubser@topic.nl>
> hw.device-type: Add Topic tdpzu9 device

- contracts/sw.os+hw.device-type/debian+jetson-xavier/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+jetson-xavier/distro-config.tpl
> jetson-xavier-agx: Update L4T in base images

- contracts/sw.os+hw.device-type/debian+jetson-xavier-nx-devkit-emmc/distro-config.tpl
- contracts/sw.os+hw.device-type/debian+jetson-xavier-nx-devkit/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+jetson-xavier-nx-devkit-emmc/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+jetson-xavier-nx-devkit/distro-config.tpl
> sw.os - hw.device-type: Update Xavier NX SD and Xavier NX eMMC to L4T 32.7.1

- contracts/sw.stack/python/contract.json
> Add libffi3.4 linked python binaries

- contracts/hw.device-type/tdpzu9/contract.json
Remove "V1R2" version from Topic Device Name
Signed-off-by: Francois Loubser <francois.loubser@topic.nl>
> hw.device-type: fix tdpzu9 device name

- contracts/hw.device-type/generic-amd64/contract.json
- contracts/hw.device-type/genericx86-64-ext/contract.json
https://jel.ly.fish/brainstorm-topic-91cbeb3d-cd66-465e-bb79-08d1ae8174cf
> x86-64 device types rename

- contracts/hw.device-type/generic-amd64/contract.json
This device type should be public
Signed-off-by: Joseph Kogut <joseph@balena.io>
> generic-amd64: disable private

- contracts/hw.device-type/generic-amd64/generic-amd64.svg
Signed-off-by: Joseph Kogut <joseph@balena.io>
> generic-amd64: update logo to be vendor agnostic

- contracts/sw.stack/node/contract.json
> Add node v18.8.0

- contracts/sw.os+hw.device-type/debian+jetson-agx-orin-devkit/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+jetson-agx-orin-devkit/distro-config.tpl
> sw.os+hw.device-type: Add distro-config.tpl for jetson-agx-orin-devkit

- contracts/sw.stack/node/contract.json
> Add node v18.12.0

- contracts/sw.stack/python/contract.json
Update pip to v22.3 and setuptools to v65.5.0.
> Add Python v3.11.0 v3.10.8 v3.9.15 v3.8.15 and v3.7.15

- contracts/sw.stack/node/contract.json
> Add node v18.12.1

- contracts/sw.stack/node/contract.json
> Add node v19.2.0

- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-aspnet+alpine/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-aspnet+alpine/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-aspnet+debian/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-aspnet+debian/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-aspnet+debian@buster/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-aspnet+debian@buster/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-aspnet+ubuntu/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-aspnet+ubuntu/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-runtime+alpine/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-runtime+alpine/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-runtime+debian/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-runtime+debian/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-runtime+debian@buster/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-runtime+debian@buster/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-runtime+ubuntu/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-runtime+ubuntu/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-sdk+alpine/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-sdk+alpine/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-sdk+debian/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-sdk+debian/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-sdk+debian@buster/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-sdk+debian@buster/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-sdk+ubuntu/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/dotnet@7.0-sdk+ubuntu/run.tpl
> Add partials for dotnet v7

- contracts/sw.stack/node/contract.json
> Add node v19.3.0 v16.19.0 and v14.21.2

- .github/workflows/flowzone.yml
> Flowzone: Use inherited secrets

- contracts/sw.stack/node/contract.json
> Add node v18.13.0 and v19.4.0

- contracts/sw.stack/golang/contract.json
> Add golang v1.19.5 and v1.18.10

- contracts/sw.stack/golang/contract.json
> Add Golang v1.20.1 and v1.19.6

- contracts/sw.stack/node/contract.json
> Add node v19.6.1 v18.14.1 v16.19.1 and v14.21.3

- contracts/hw.device-type/radxa-zero/contract.json
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>
> patch: Fix spelling for eMMC in Radxa-zero contract

- contracts/hw.device-type/iot-gate-imx8plus/contract.json
Bring in the latest updates from the coffee file
in the device repository.
Changelog-entry: iot-gate-imx8plus: Update provisioning instructions
> iot-gate-imx8plus: Update provisioning instructions

- contracts/sw.stack+sw.os+hw.device-type/golang+alpine/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/golang+alpine/run.tpl
> Fix a condition where /etc/nsswitch.conf exists and the build fails

- contracts/sw.stack+sw.os+hw.device-type/node+alpine/build.tpl
- contracts/sw.stack+sw.os+hw.device-type/node+alpine/run.tpl
- contracts/sw.stack+sw.os+hw.device-type/python+alpine/run.tpl
> Fix conditional when installing libssl1.1

- contracts/hw.device-type/iot-gate-imx8plus/contract.json
> iot-gate-imx8plus: Improve provisioning instructions for Windows

- contracts/sw.os/alpine/contract.json
- contracts/sw.stack/dotnet/contract.json
- contracts/sw.stack/golang/contract.json
- contracts/sw.stack/python/contract.json
Resolves: https://github.com/balena-io-library/base-images/issues/870
> Add alpine 3.18

- contracts/hw.device-type/bluechiptechnology-tm3/contract.json
> hw.device-type: Modify bluechiptechnology-tm3

- contracts/hw.device-type/advantech-ecu1370/advantech_logo.svg
- contracts/hw.device-type/advantech-ecu1370/contract.json
> Add Advantech ECU1370 to hardware contract.

- contracts/hw.device-type/beagleplay/contract.json
Signed-off-by: Sidd-Gupta sidd.gupta@zylum.in
> hw.device-type: Disable bluetooth until this feature is officially supported

- contracts/hw.device-type/beagleplay/contract.json
> beagleplay: Fix provisioning instructions

- contracts/sw.stack/openjdk/contract.json
Add versionList to OpenJDK
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
> patch: Add versionList to OpenJDK

- contracts/hw.device-type/beagleplay/contract.json
> hw.device-type: Remove superfluous instructions for beagleplay

- contracts/sw.os+hw.device-type/debian+jetson-agx-orin-devkit/distro-config.tpl
- contracts/sw.os+hw.device-type/debian+jetson-orin-nano-devkit-nvme/distro-config.tpl
- contracts/sw.os+hw.device-type/debian+jetson-orin-nano-seeed-j3010/distro-config.tpl
- contracts/sw.os+hw.device-type/debian+jetson-orin-nx-seeed-j4012/distro-config.tpl
- contracts/sw.os+hw.device-type/debian+jetson-orin-nx-xavier-nx-devkit/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+jetson-agx-orin-devkit/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+jetson-orin-nano-devkit-nvme/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+jetson-orin-nano-seeed-j3010/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+jetson-orin-nx-seeed-j4012/distro-config.tpl
- contracts/sw.os+hw.device-type/ubuntu+jetson-orin-nx-xavier-nx-devkit/distro-config.tpl
> sw.os+hw.device-type: Update all Orin devices to r36.3 in sources.list

- contracts/sw.os/alpine/contract.json
- contracts/sw.stack/dotnet/contract.json
- contracts/sw.stack/golang/contract.json
- contracts/sw.stack/python/contract.json
> Add alpine 3.20

- contracts/hw.device-type/jetson-orin-nano-seeed-j3010/contract.json
- contracts/hw.device-type/jetson-orin-nx-seeed-j4012/contract.json
As per the internal discussion: https://balena.zulipchat.com/#narrow/channel/345884-aspect.2Fanalytics/topic/Number.20of.20provisioned.20device.20per.20.22family.22.20over.20time/near/483956162
> hw.device-type: Rename Seeed J3010 and J4012 to include module name

- contracts/hw.device-type/forecr-dsb-ornx-orin-nano-8gb/contract.json
... to match the carrier board more clearly. The slug stays the same as the device is already present in the API.
> Forecr DSB ORNX: Update device name

- contracts/sw.os/alpine/contract.json
> Add alpine 3.21

- contracts/sw.os/debian/contract.json
> Mark Bookworm as the default version for Debian

- contracts/hw.device-type/jetson-agx-orin-devkit-64gb/contract.json
- contracts/hw.device-type/jetson-orin-nano-devkit-nvme/contract.json
- contracts/hw.device-type/jetson-orin-nano-seeed-j3010/contract.json
- contracts/hw.device-type/jetson-orin-nx-seeed-j4012/contract.json
- contracts/hw.device-type/jetson-orin-nx-xavier-nx-devkit/contract.json
> hw.device-type: Update links to docs for UEFI version checking

- contracts/hw.device-type/imx6ul-var-dart/contract.json
... to take into account that SW1 and SW2 and switches and not buttons.
> imx6ul-var-dart: Update provisioning instructions
