contracts/sw.os/ubuntu/contract.json, contracts/sw.stack/dotnet/contract.json, contracts/sw.stack/openjdk/contract.json, contracts/sw.stack/python/contract.json
This Pr has the following changes:
- ubuntu: Add support for new Ubuntu versions (Disco and Eoan) and drop support for Ubuntu Trusty and Artful (https://hub.docker.com/_/ubuntu/).
- dotnet: Add support for .NET Core v3.0.0
=> Few base images updates

contracts/sw.os+arch.sw/debian+i386-nlp/base-dependencies.tpl, contracts/sw.os+arch.sw/debian/base-dependencies.tpl, contracts/sw.os+arch.sw/debian@buster/base-dependencies.tpl, contracts/sw.os+arch.sw/debian@jessie+aarch64/base-dependencies.tpl, contracts/sw.os+arch.sw/debian@jessie/base-dependencies.tpl, contracts/sw.os+arch.sw/ubuntu+i386-nlp/base-dependencies.tpl, contracts/sw.os+arch.sw/ubuntu/base-dependencies.tpl
Make sure the cleanup command will not fail when removing non-existent directories
=> install_packages: Fix cleanup command

contracts/sw.os/alpine/contract.json, contracts/sw.os/debian/contract.json, contracts/sw.os/fedora/contract.json, contracts/sw.os/ubuntu/contract.json, contracts/sw.stack/dotnet/contract.json, contracts/sw.stack/golang/contract.json, contracts/sw.stack/node/contract.json, contracts/sw.stack/python/contract.json
- Update for latest test scripts (see https://github.com/balena-io-library/base-images/pull/594)
- Add Go v1.13.3  and v1.12.12
=> Few base-images updates

contracts/sw.os+arch.sw/alpine@3.11+armv7hf/from.tpl, contracts/sw.os/alpine/contract.json, contracts/sw.stack/node/contract.json, contracts/sw.stack/python/contract.json
This PR contains the following changes: 
- alpine: Add support for Alpine Linux v3.11
- node: Add v13.5.0 v12.14.0 v10.18.0 and v8.17.0. Update Yarn to v1.21.1.
=> Few base image updates

contracts/hw.device-type/nitrogen8mm-dwe/contract.json
Add support for new device type - Nitrogen8MM DWE
=> device: Add Nitrogen8MM DWE board

contracts/hw.device-type/m2pcie-tx2/contract.json
Add support for new device type - m2pcie-tx2
=> device: Add Nvidia Jetson TX2 with PCIe M.2 Slot Enabled

contracts/sw.os+hw.device-type/debian+coral-dev/dependencies.tpl, contracts/sw.os+hw.device-type/debian@jessie+coral-dev/dependencies.tpl, contracts/sw.os+hw.device-type/ubuntu+coral-dev/dependencies.tpl, contracts/sw.os+hw.device-type/ubuntu@focal+coral-dev/dependencies.tpl
Except debian jessie and ubuntu focal due to incompatible python version
=> Add coral package sources to debian and ubuntu images

contracts/sw.os+arch.sw/alpine+armv7hf/from.tpl, contracts/sw.os+arch.sw/alpine/build.tpl, contracts/sw.os+arch.sw/alpine@3.10+armv7hf/from.tpl, contracts/sw.os+arch.sw/alpine@3.11+armv7hf/from.tpl, contracts/sw.os+arch.sw/alpine@3.9+armv7hf/from.tpl, contracts/sw.os+arch.sw/alpine@edge+armv7hf/from.tpl, contracts/sw.os/alpine/contract.json, contracts/sw.stack/python/contract.json
Alpine Linux v3.6 v3.7 and v3.8 will be dropped since they are pretty old and no longer supported by official Alpine Linux Dockerhub repo.
=> Add support for Alpine Linux v3.12 and drop few old versions

contracts/sw.stack/python/contract.json
- Add Python v3.6.11 and v3.7.8, upgrade pip to v20.1.1 and setuptools to v49.1.0.
- Change latest Python tag to v3.8.3 (as mentioned in the announcement, the latest tag for balenalib Python base image will be changed to Python 3.x on July).
=> Change Python latest tag to 3.x and add support for latest releases

contracts/hw.device-type/astro-tx2/contract.json
=> astro-tx2: Add CTI Astro TX2 G+ device type

contracts/hw.device-type/jetson-xavier-nx-devkit/contract.json
Add Jetson Xavier NX Devkit SD-CARD device type
=> jetson-xavier-nx-devkit: Add device type

contracts/sw.stack/golang/contract.json, contracts/sw.stack/node/contract.json
- Add Golang v1.15.3 and v1.14.10.
- Add node v15.0.1 v14.15.0 and v10.23.0.
=> Base images updates

contracts/sw.os+hw.device-type/debian+jetson-xavier-nx-devkit-emmc/distro-config.tpl, contracts/sw.os+hw.device-type/debian+jetson-xavier-nx-devkit/distro-config.tpl, contracts/sw.os+hw.device-type/debian+jetson-xavier/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-xavier-nx-devkit-emmc/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-xavier-nx-devkit/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-xavier/distro-config.tpl
We updated the hostOS to 32.4.4 in BalenaOS
2.67.3 for the Jetson Xavier boards, let's switch to
the newer container packages now.
=> jetson-xaviers: Update repositories to 32.4

contracts/sw.os+hw.device-type/debian+jetson-tx2/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-tx2/distro-config.tpl
We updated the hostOS to 32.4.4 in BalenaOS
2.69.1 for the Jetson TX2, let's switch to
the newer container packages now.
=> jetson-tx2: Update repositories to 32.4

contracts/hw.device-type/floyd-nano/contract.json
We've updated the name in the coffee file
for this device type to show that this device
type is based on a eMMC Nano module. Let's update
the name here too.
=> device: Update name for Floyd Nano

contracts/sw.os+arch.sw/alpine/build.tpl, contracts/sw.os/alpine/contract.json, contracts/sw.stack+sw.os+hw.device-type/openjdk@16-jdk+debian/build.tpl, contracts/sw.stack+sw.os+hw.device-type/openjdk@16-jdk+debian/run.tpl, contracts/sw.stack/golang/contract.json, contracts/sw.stack/node/contract.json, contracts/sw.stack/openjdk/contract.json, contracts/sw.stack/python/contract.json
- Add golang v1.16.5 and v1.15.13.
- Update python-dbus to v1.2.16.
- Add node v16.4.0.
- Add support for Alpine Linux 3.14.
- Add openjdk-16 for amd64 and aarch64 Debian Buster.
=> Various base images updates

contracts/sw.stack+sw.os+hw.device-type/dotnet-aspnet-3.x.tpl, contracts/sw.stack+sw.os+hw.device-type/dotnet-runtime.tpl, contracts/sw.stack+sw.os+hw.device-type/dotnet-sdk.tpl
Use two spaces when verifying binary checksum
=> Update dotnet partials

contracts/hw.device-type/genericx86-64-ext/contract.json
Disable wireless and bluetooth for genericx86-64-ext DT, as these are
not built-in and provided by default for this device type. This allows
core tests to pass in Leviathan, as it's not assumed that these devices
are present.
Signed-off-by: Joseph Kogut <joseph@balena.io>
=> hw.device-type: genericx86-64-ext: disable wlan/bluetooth

contracts/sw.os+hw.device-type/debian+jetson-nano-2gb-devkit/distro-config.tpl, contracts/sw.os+hw.device-type/debian+jetson-nano-emmc/distro-config.tpl, contracts/sw.os+hw.device-type/debian+jetson-nano/distro-config.tpl, contracts/sw.os+hw.device-type/debian+jetson-tx2/distro-config.tpl, contracts/sw.os+hw.device-type/debian+jetson-xavier-nx-devkit-emmc/distro-config.tpl, contracts/sw.os+hw.device-type/debian+jetson-xavier-nx-devkit/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-nano-2gb-devkit/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-nano-emmc/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-nano/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-tx2/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-xavier-nx-devkit-emmc/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-xavier-nx-devkit/distro-config.tpl
This is part one which updates the base images for
the following devices, which have the kernel updated
to L4T 32.6.1 in the OS image:
- Jetson Nano 2GB
- Jetson Nano eMMC
- Jetson Nano SD-CARD
- Jetson Xavier NX
- Jetson TX2 NX
The following devices will have the base
images updated in a subsequent commit, after
new OS images are released for them:
- Jetson TX2
- Jetson Xavier AGX
=> hw.device-type: Update sources.list to L4T 32.6.1

contracts/hw.device-type/raspberrypi0-2w-64/contract.json
This board's correct name as per its nomenclature is [Raspberry Pi Zero 2 W](https://www.raspberrypi.com/products/raspberry-pi-zero-2-w/)
Context: https://github.com/balena-io/docs/issues/2018#issuecomment-1040788307
Fixing it here to fix it everywhere
=> patch: Update RPi0 2 W's name

contracts/hw.device-type/nanopi-r2c/contract.json
The device does not have any WiFi chipset so let's correct that
=> hw.device-type: Correct NanoPi R2C device contract

contracts/sw.os-image/balenaos/contract.json, contracts/sw.os/balenaos/contract.json
These will be used by the OS builders when deploying OS releases.
=> Add sw.os and sw.os-image contracts

contracts/hw.device-type/rockpi-4b-rk3399/contract.json
LED is not supported for this DT in the device
repository, let's set it to false here so that
the tests are aware of this being unsupported.
=> hw.device-type: Set LED to false for rockpi-4b

contracts/hw.device-type/generic-aarch64/contract.json, contracts/hw.device-type/generic-armv7ahf/contract.json, contracts/hw.device-type/generic/contract.json, contracts/hw.device-type/iot-gate-imx8/contract.json
While testing new contract based instruction generation, I found a couple incorrect partials in the contacts. This resolves these issues.
Signed-off-by: Micah Halter <micah@balena.io>
=> Fix incorrect partials in device type contracts

README.md
Docs written by general observations and clarifcations provided by devices team + this PR: https://github.com/balena-io/contracts/pull/236
Zuilp: https://balena.zulipchat.com/#narrow/stream/345889-balena-io.2Fos/topic/contracts.20accuracy.20for.20instructions
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>
=> patch: Add docs to contracts for instructions partials

contracts/hw.device-type/jetson-tx2-nx-devkit/contract.json, contracts/hw.device-type/jn30b-nano/contract.json, contracts/hw.device-type/owa5x/contract.json, contracts/hw.device-type/radxa-cm3-rpicm4-ioboard/contract.json, contracts/hw.device-type/radxa-zero/contract.json, contracts/hw.device-type/raspberrypicm4-ioboard/contract.json
- The Jetson TX2 NX has an eMMC and no SD-CARD slot
- The JN30B Nano uses the eMMC module and not the SD-CARD one
- The Radxa CM3 on RPI CM4 IOBoard as well as the Radxa zero use rockchip software tools in order to put the eMMC in mass-storage mode
- The CM4 module comes in two flavors: one with eMMC and the Lite version which uses the carrier board sd-card slot to load the image. Both use the same balenaOS image. I switched the storage to internal for this DT because it *may* have one, but this solely depends on the actual module. Another consideration is that this DT can also boot from a USB stick or a NVME drive connected to the mPCIE port.
=> hw.device-type: Various fixes

contracts/sw.stack+sw.os+hw.device-type/node+alpine/build.tpl, contracts/sw.stack+sw.os+hw.device-type/node+alpine/run.tpl, contracts/sw.stack+sw.os+hw.device-type/node+debian/build.tpl, contracts/sw.stack+sw.os+hw.device-type/node+debian/run.tpl, contracts/sw.stack+sw.os+hw.device-type/node+fedora/build.tpl, contracts/sw.stack+sw.os+hw.device-type/node+fedora/run.tpl, contracts/sw.stack+sw.os+hw.device-type/node+ubuntu/build.tpl, contracts/sw.stack+sw.os+hw.device-type/node+ubuntu/run.tpl
The `unsafe-perm` config option has been dropped in `npm` 9, trying to set it ends with an error and therefore fails the build. With this patch the build script parses the major version from `npm --version` and only sets `unsafe-perm` on `npm` 8 and older.
=> node: do not set unsafe-perm with npm 9 and newer

contracts/hw.device-type/iot-gate-imx8/contract.json
To specify that the iot-gate-imx8 doesn't have an identification LED
=> hw/device-type: Update contract.json for iot-gate-imx8

contracts/sw.os+hw.device-type/debian+jetson-orin-nano-devkit-nvme/distro-config.tpl, contracts/sw.os+hw.device-type/ubuntu+jetson-orin-nano-devkit-nvme/distro-config.tpl
Connects-to: https://github.com/balena-os/balena-jetson-orin/pull/212
Tested 35.3 on Orin Nano Devkit NVME:
```
cp clock ../../bin/aarch64/linux/release
CUDA Clock sample
GPU Device 0: "Ampere" with compute capability 8.7
Average clocks/block = 1965.765625
```
=> sw.os+hw.device-type: Add ubuntu and debian distro configs for Orin Nano

contracts/sw.stack/openjdk/contract.json
=> Remove OpenJDK v7 as it has been removed from alpine edge

contracts/hw.device-type/raspberrypi5/contract.json
As the device was previously private, the `is_private` needs to be explicitly set to false for the device type to become public.
=> raspberrypi5: Explicitly flag as public for the switch to apply

contracts/hw.device-type/raspberrypi5/contract.json
There won't be a 32bits OS for this device type.
=> raspberrypi5: remove reference to 64bits in display name

contracts/hw.device-type/bluechiptechnology-tm3/contract.json
I found https://github.com/balena-io/contracts/blob/master/contracts/hw.device-type/rockpi-4b-rk3399/contract.json and https://docs.balena.io/learn/getting-started/rockpi-4b-rk3399/nodejs/ which appear to have the same installation process 
Which I've adapted below -
* Wait for writing of balenaOS to complete.
* Remove the SD card from the host machine.
* Insert the freshly flashed SD card into the TM3
* Warning! This will also completely erase internal storage medium, so please make a backup first.
* Connect power to the TM3
* Wait for the TM3 to finish flashing and shutdown. Please wait until screen and Ethernet green LED are off.
* Remove the SD card from the TM3.
* Remove and re-connect power to the TM3 to boot the device.
I wasn't quite sure how the 'partials' maps …
=> hw.device-type: Modify bluechiptechnology-tm3

contracts/hw.device-type/lcbzu9/contract.json
Make flasher image available for download to boot lcbzu9 from eMMC
Changelog-entry: patch
=> lcbzu9: boot from internal storage

contracts/hw.device-type/asus-tinker-board-s/contract.json
Folks, the link for the Tinker Board wiki instructions is dead which results in the Getting Started instructions having a dead link. Can you suggest a replacement for the link in the current documentation please or I would like to remove it/change the wording a bit for users to make sense. Let me know what you recommend? @acostach @floion 
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
=> patch: Remove Tinker Board Wiki link going 404

contracts/hw.device-type/imx8mp-var-dart/contract.json
This was added by mistake as private when it is supposed to be a public dt.
=> hw.device-type: Fix device type is_private flag for imx8mp-var-dart

contracts/hw.device-type/iot-gate-imx8plus-d1d8/contract.json, contracts/hw.device-type/iot-gate-imx8plus/contract.json, contracts/hw.device-type/radxa-cm3-rpicm4-ioboard/contract.json, contracts/hw.device-type/radxa-zero/contract.json
If hyperlinks are unquoted, a target=blank is added and entire link is broken in the dashboard. This doesn't happen for devices which use quoted links, like for example the CM4.
=> hw.device-type: Fix hyperlinks in provisioning instructions

contracts/sw.stack/node/contract.json
Planning to add alpine in a follow-up once
we get the jenkins job to work and will then
also mark 20.12.0 as the latest.
=> Add node v20.12.0 for debian

contracts/sw.os/fedora/contract.json
See: https://endoflife.date/fedora
=> Remove Fedora 36 since it's EOL

contracts/sw.os/ubuntu/contract.json
See: https://endoflife.date/ubuntu
=> Remove Ubuntu Lunar 23.04 since it's EOL

contracts/hw.device-type/jetson-agx-orin-devkit-64gb/contract.json
The AGX Orin 64GB should be provisioned on the eMMC by default as per the internal thread https://balena.zulipchat.com/#narrow/stream/346009-aspect.2Fcustomer-success/topic/Get.20feedback.20on.20draft.20balenaOS.20with.20L4T.2036.2E3.20for.20Jetson.20Orin/near/455889690
We thus update the provisioning instructions accordingly
=> hw.device-type: Update provisioning instructions for AGX Orin 64GB

contracts/sw.os+hw.device-type/ubuntu@noble+coral-dev/dependencies.tpl, contracts/sw.os+hw.device-type/ubuntu@noble+raspberry-pi2/dependencies.tpl, contracts/sw.os+hw.device-type/ubuntu@noble+raspberrypi0-2w-64/dependencies.tpl, contracts/sw.os+hw.device-type/ubuntu@noble+raspberrypi3-64/dependencies.tpl, contracts/sw.os+hw.device-type/ubuntu@noble+raspberrypi3/dependencies.tpl, contracts/sw.os+hw.device-type/ubuntu@noble+raspberrypi4-64/dependencies.tpl, contracts/sw.os+hw.device-type/ubuntu@noble+raspberrypi400-64/dependencies.tpl, contracts/sw.os+hw.device-type/ubuntu@noble+revpi-core-3/dependencies.tpl, contracts/sw.os/ubuntu/contract.json, contracts/sw.stack/dotnet/contract.json, contracts/sw.stack/python/contract.json
```
- Add support for Ubuntu Noble.
```
=> Add support for Ubuntu Noble

contracts/hw.device-type/iotdin-imx8p-d1d8/contract.json, contracts/hw.device-type/iotdin-imx8p/contract.json
Disable bluetooth and wifi in the devices contracts files. Reason: the CompuLab Autokit came without an IFM-WB i/o module.
=> iotdin-imx8p: Update the devices contract

contracts/hw.device-type/jetson-agx-orin-devkit-64gb/contract.json, contracts/hw.device-type/jetson-orin-nano-devkit-nvme/contract.json, contracts/hw.device-type/jetson-orin-nano-seeed-j3010/contract.json, contracts/hw.device-type/jetson-orin-nx-seeed-j4012/contract.json, contracts/hw.device-type/jetson-orin-nx-xavier-nx-devkit/contract.json
Connects-to: https://balena.fibery.io/Work/Project/Radically-change-Nvidia-Orin-provisioning-929
=> contracts/hw.device-type: Update instructions for Orin flasher types

contracts/hw.device-type/jetson-agx-orin-devkit-64gb/contract.json, contracts/hw.device-type/jetson-orin-nano-devkit-nvme/contract.json, contracts/hw.device-type/jetson-orin-nano-seeed-j3010/contract.json, contracts/hw.device-type/jetson-orin-nx-seeed-j4012/contract.json, contracts/hw.device-type/jetson-orin-nx-xavier-nx-devkit/contract.json
=> hw.device-type: Fix compatibility with existing sdk structure

contracts/hw.device-type/forecr-dsb-ornx-lan-orin-nx-16gb/contract.json, contracts/hw.device-type/forecr-dsb-ornx-orin-nano-8gb/contract.json, contracts/hw.device-type/intel-edison/contract.json, contracts/hw.device-type/iot-gate-imx8plus-d1d8/contract.json, contracts/hw.device-type/iot-gate-imx8plus/contract.json, contracts/hw.device-type/iotdin-imx8p-d1d8/contract.json, contracts/hw.device-type/iotdin-imx8p/contract.json, contracts/hw.device-type/jetson-agx-orin-devkit-64gb/contract.json, contracts/hw.device-type/jetson-orin-nano-devkit-nvme/contract.json, contracts/hw.device-type/jetson-orin-nano-seeed-j3010/contract.json, contracts/hw.device-type/jetson-orin-nx-seeed-j4012/contract.json, contracts/hw.device-type/jetson-orin-nx-xavier-nx-devkit/contract.json, contracts/hw.device-type/radxa-cm3-rpicm4-ioboard/contract.json, contracts/hw.device-type/radxa-zero/contract.json, contracts/hw.device-type/raspberrypicm4-ioboard/contract.json
... as per the internal thread
https://balena.zulipchat.com/#narrow/channel/350505-aspect.2Fgrowth/topic/Improving.20Jetson-flash.20documentation/near/493450821
Due to recent changes in the renderer, HTML links are no longer displayed.
=> hw.device-type: Switch to using markdown for links

contracts/sw.os/alpine/contract.json
https://balena.zendesk.com/agent/tickets/4549
=> Mark alpine 3.21 as the default alpine version

contracts/sw.os/ubuntu/contract.json, contracts/sw.stack+sw.os+hw.device-type/dotnet@3.1-aspnet+ubuntu@bionic/build.tpl, contracts/sw.stack+sw.os+hw.device-type/dotnet@3.1-aspnet+ubuntu@bionic/run.tpl, contracts/sw.stack+sw.os+hw.device-type/dotnet@3.1-runtime+ubuntu@bionic/build.tpl, contracts/sw.stack+sw.os+hw.device-type/dotnet@3.1-runtime+ubuntu@bionic/run.tpl, contracts/sw.stack+sw.os+hw.device-type/dotnet@3.1-sdk+ubuntu@bionic/build.tpl, contracts/sw.stack+sw.os+hw.device-type/dotnet@3.1-sdk+ubuntu@bionic/run.tpl, contracts/sw.stack/dotnet/contract.json, contracts/sw.stack/openjdk/contract.json, contracts/sw.stack/python/contract.json
Focal is EOL in May 2025
Bionic was EOL in May 2023
Xenial was EOL in April 2021
=> Remove EOL Ubuntu distros

contracts/sw.stack/dotnet/contract.json, contracts/sw.stack/python/contract.json
=> Remove Ubuntu Lunar 23.04 leftovers from dotnet & python contracts
